[project]
name = "machine-learning-1"
version = "0.1.0"
description = "Repository for ml course at my university (FER)"
readme = "README.md"
requires-python = ">=3.8.20"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyterlab>=4.3.8",
    "matplotlib>=3.7.5",
    "numpy<2.0",
    "pandas>=2.0.3",
    "scikit-learn<1.4",
    "scipy<1.11",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "black>=24.8.0",
    "pytest>=8.3.5",
    "ruff>=0.13.2",
]


[tool.ruff]
target-version = "py38"
line-length = 88
select = ["E","F","I"]
exclude = ["venv",".venv","build","dist"]

[tool.black]
line-length = 88
target-version = ["py38"]
